export const LOCATIONS: string[] = [
  'Semua Jawa Barat',
  'Bandung',
  'Bandung Barat',
  'Banjar',
  'Bekasi',
  'Bogor',
  'Ciamis',
  'Cianjur',
  'Cimahi',
  'Cirebon',
  'Depok',
  'Garut',
  'Indramayu',
  'Karawang',
  'Kuningan',
  'Majalengka',
  'Pangandaran',
  'Purwakarta',
  'Subang',
  'Sukabumi',
  'Sumedang',
  'Tasikmalaya',
];

export const WEST_JAVA_ADMIN_REGIONS: { type: 'Kota' | 'Kabupaten'; name: string; aliases: string[] }[] = [
  { type: 'Kota', name: 'Kota Bandung', aliases: ['bandung', 'kota bandung', 'bdg'] },
  { type: 'Kabupaten', name: 'Kabupaten Bandung', aliases: ['kabupaten bandung', 'kab. bandung', 'soreang', 'baleendah', 'dayeuhkolot', 'majalaya', 'ciwidey', 'rancaekek', 'cicalengka', 'banjaran'] },
  { type: 'Kota', name: 'Kota Cimahi', aliases: ['cimahi', 'kota cimahi', 'leuwigajah', 'baros'] },
  { type: 'Kabupaten', name: 'Kabupaten Bandung Barat', aliases: ['bandung barat', 'kabupaten bandung barat', 'kab. bandung barat', 'kbb', 'padalarang', 'lembang', 'ngamprah', 'batujajar', 'parongpong'] },
  { type: 'Kabupaten', name: 'Kabupaten Sumedang', aliases: ['sumedang', 'kabupaten sumedang', 'kab. sumedang', 'jatinangor', 'tanjungsari'] },
  { type: 'Kabupaten', name: 'Kabupaten Garut', aliases: ['garut', 'kabupaten garut', 'kab. garut', 'tarogong'] },
  { type: 'Kabupaten', name: 'Kabupaten Cianjur', aliases: ['cianjur', 'kabupaten cianjur', 'kab. cianjur', 'cipanas'] },
  { type: 'Kota', name: 'Kota Sukabumi', aliases: ['kota sukabumi'] },
  { type: 'Kabupaten', name: 'Kabupaten Sukabumi', aliases: ['sukabumi', 'kabupaten sukabumi', 'kab. sukabumi', 'cibadak', 'cicurug', 'palabuhanratu', 'cisaat'] },
  { type: 'Kota', name: 'Kota Bogor', aliases: ['kota bogor'] },
  { type: 'Kabupaten', name: 'Kabupaten Bogor', aliases: ['bogor', 'kabupaten bogor', 'kab. bogor', 'cibinong', 'cileungsi', 'gunung putri', 'citeureup', 'jonggol', 'parung'] },
  { type: 'Kota', name: 'Kota Depok', aliases: ['depok', 'kota depok', 'margonda', 'cinere', 'sawangan', 'cimanggis'] },
  { type: 'Kota', name: 'Kota Bekasi', aliases: ['kota bekasi'] },
  { type: 'Kabupaten', name: 'Kabupaten Bekasi', aliases: ['bekasi', 'kabupaten bekasi', 'kab. bekasi', 'cikarang', 'cibitung', 'tambun'] },
  { type: 'Kabupaten', name: 'Kabupaten Karawang', aliases: ['karawang', 'kabupaten karawang', 'kab. karawang', 'cikampek', 'telukjambe', 'klari'] },
  { type: 'Kabupaten', name: 'Kabupaten Purwakarta', aliases: ['purwakarta', 'kabupaten purwakarta', 'kab. purwakarta', 'jatiluhur'] },
  { type: 'Kabupaten', name: 'Kabupaten Subang', aliases: ['subang', 'kabupaten subang', 'kab. subang', 'kalijati', 'patimban'] },
  { type: 'Kabupaten', name: 'Kabupaten Indramayu', aliases: ['indramayu', 'kabupaten indramayu', 'kab. indramayu', 'jatibarang'] },
  { type: 'Kota', name: 'Kota Cirebon', aliases: ['kota cirebon'] },
  { type: 'Kabupaten', name: 'Kabupaten Cirebon', aliases: ['cirebon', 'kabupaten cirebon', 'kab. cirebon', 'sumber', 'kedawung', 'weru'] },
  { type: 'Kabupaten', name: 'Kabupaten Majalengka', aliases: ['majalengka', 'kabupaten majalengka', 'kab. majalengka', 'kertajati', 'jatiwangi'] },
  { type: 'Kabupaten', name: 'Kabupaten Kuningan', aliases: ['kuningan', 'kabupaten kuningan', 'kab. kuningan', 'cilimus'] },
  { type: 'Kabupaten', name: 'Kabupaten Ciamis', aliases: ['ciamis', 'kabupaten ciamis', 'kab. ciamis', 'banjarsari'] },
  { type: 'Kota', name: 'Kota Banjar', aliases: ['banjar', 'kota banjar'] },
  { type: 'Kabupaten', name: 'Kabupaten Pangandaran', aliases: ['pangandaran', 'kabupaten pangandaran', 'kab. pangandaran', 'parigi'] },
  { type: 'Kota', name: 'Kota Tasikmalaya', aliases: ['kota tasikmalaya'] },
  { type: 'Kabupaten', name: 'Kabupaten Tasikmalaya', aliases: ['tasikmalaya', 'kabupaten tasikmalaya', 'kab. tasikmalaya', 'singaparna'] },
];

export const CATEGORIES: string[] = [
  'Semua Kategori',
  'Administrasi',
  'IT',
  'Marketing',
  'Sales',
  'Customer Service',
  'Pabrik',
  'Operator',
  'Driver',
  'Logistik',
  'Keuangan',
  'Kesehatan',
  'Pendidikan',
  'Hotel',
  'Restoran',
  'Retail',
  'Freelance',
  'Remote',
  'Lainnya',
];
